set nocompatible
set incsearch "show search
set number "line numbers
syntax on "syntax highlighting
set hidden "allow hidden buffer
execute pathogen#infect()
call pathogen#helptags()

" Nerd Tree
map <C-\> :NERDTreeToggle<CR>

" Tabs, etc
set nowrap " don't wrap lines
set tabstop=2 "2 spaces per tab


" Colorscheme
colorscheme monokai
set t_Co=256

